import type { ComponentExport } from "./component-scan";

/**
 * Ladle scaffold planner (pure). Turns the components a project exports into the exact set of files
 * Visual Guard would write to make per-component capture possible: a minimal `.ladle/config.mjs` and one
 * co-located `<Component>.stories.tsx` per component file (one `Default` story rendering the primary
 * component). **Idempotent**: any path that already exists is skipped (never clobbering a user-edited
 * story or config), so re-running only adds stories for newly-added components.
 *
 * Pure — `fileExists` is injected — so the plan is fully unit-testable; the impure `scripts/harness.ts`
 * shell reads files, calls this, and (on --apply) writes the planned files behind a path guard.
 */

/** The dev dependency a Ladle harness needs in the USER's project (pinned so discovery's meta shape matches). */
export const LADLE_DEV_DEPENDENCY = { name: "@ladle/react", version: "^4.1.2" } as const;

export interface ScaffoldFile {
  /** Project-relative POSIX path to write. */
  path: string;
  contents: string;
  role: "config" | "story";
}

export interface NeedsPropsWarning {
  component: string;
  /** The component source file. */
  file: string;
  /** The generated story file the user should edit to pass props. */
  story: string;
}

export interface ScaffoldPlan {
  harness: "ladle";
  /** Files to write (config + per-component stories), excluding any that already exist. */
  files: ScaffoldFile[];
  /** Paths skipped because they already exist (user-owned / idempotency). */
  skipped: string[];
  /** The dev dependency to add to the user's package.json (the shell adds it only if absent). */
  devDependency: { name: string; version: string };
  /** Primary components whose generated story likely renders blank without props (advisory). */
  needsPropsWarnings: NeedsPropsWarning[];
  /** Distinct component files discovered (planned or skipped). */
  componentCount: number;
}

export interface PlanOptions {
  components: ComponentExport[];
  /** Predicate: does a project-relative path already exist? (shell → existsSync; tests → a Set). */
  fileExists: (path: string) => boolean;
  /** The component root dir (project-relative), used for the Ladle stories glob. Defaults to "src". */
  componentRoot?: string;
  devDependency?: { name: string; version: string };
}

function baseNoExt(file: string): string {
  const last = file.split("/").pop() ?? file;
  return last.replace(/\.[^.]+$/, "");
}

/** The story file for a component file: co-located, `.stories.<tsx|jsx>` matching the source flavor. */
function storyPathFor(file: string): string {
  const ext = /\.(jsx|js)$/.test(file) ? "jsx" : "tsx";
  return file.replace(/\.[^./]+$/, `.stories.${ext}`);
}

/** The relative import specifier from the co-located story to its component (extension stripped). */
function importPathFor(file: string): string {
  return `./${baseNoExt(file)}`;
}

/** Primary component for a file: the default export, else the export named like the file, else the first. */
function pickPrimary(file: string, exports: ComponentExport[]): ComponentExport | undefined {
  const def = exports.find((e) => e.kind === "default");
  if (def !== undefined) return def;
  const base = baseNoExt(file).toLowerCase();
  return exports.find((e) => e.name.toLowerCase() === base) ?? exports[0];
}

const HEADER =
  "// Generated by Visual Guard. Safe to edit — Visual Guard never overwrites an existing story file.";

function renderStory(primary: ComponentExport, importPath: string): string {
  const imp =
    primary.kind === "default"
      ? `import ${primary.name} from "${importPath}";`
      : `import { ${primary.name} } from "${importPath}";`;
  if (primary.likelyNeedsProps) {
    return (
      [
        HEADER,
        imp,
        "",
        `// TODO(visual-guard): <${primary.name}> looks like it needs props to render — pass them below`,
        "// so the captured snapshot is meaningful (otherwise it may render blank).",
        `export const Default = () => <${primary.name} /* prop="value" */ />;`,
      ].join("\n") + "\n"
    );
  }
  return [HEADER, imp, "", `export const Default = () => <${primary.name} />;`].join("\n") + "\n";
}

function ladleConfig(componentRoot: string): string {
  const glob = `${componentRoot.replace(/\/+$/, "")}/**/*.stories.{tsx,jsx}`;
  return (
    [
      "// Generated by Visual Guard. Ladle config — edit freely.",
      "export default {",
      `  stories: "${glob}",`,
      "};",
    ].join("\n") + "\n"
  );
}

export function planLadleScaffold(opts: PlanOptions): ScaffoldPlan {
  const componentRoot =
    opts.componentRoot !== undefined && opts.componentRoot.length > 0 ? opts.componentRoot : "src";
  const devDependency = opts.devDependency ?? { ...LADLE_DEV_DEPENDENCY };

  const byFile = new Map<string, ComponentExport[]>();
  for (const component of opts.components) {
    const list = byFile.get(component.file) ?? [];
    list.push(component);
    byFile.set(component.file, list);
  }

  const files: ScaffoldFile[] = [];
  const skipped: string[] = [];
  const needsPropsWarnings: NeedsPropsWarning[] = [];

  const configPath = ".ladle/config.mjs";
  if (opts.fileExists(configPath)) {
    skipped.push(configPath);
  } else {
    files.push({ path: configPath, contents: ladleConfig(componentRoot), role: "config" });
  }

  for (const file of [...byFile.keys()].sort()) {
    const exports = byFile.get(file);
    if (exports === undefined) continue;
    const primary = pickPrimary(file, exports);
    if (primary === undefined) continue;
    const path = storyPathFor(file);
    // A *.stories file should never have been scanned as a component, but guard against self-write.
    if (path === file) continue;
    if (opts.fileExists(path)) {
      skipped.push(path);
      continue;
    }
    files.push({ path, contents: renderStory(primary, importPathFor(file)), role: "story" });
    if (primary.likelyNeedsProps) {
      needsPropsWarnings.push({ component: primary.name, file, story: path });
    }
  }

  return {
    harness: "ladle",
    files,
    skipped,
    devDependency,
    needsPropsWarnings,
    componentCount: byFile.size,
  };
}
